apiVersion: apps/v1
kind: Deployment
metadata:
  name: frozenyogurtshop-revathi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frozenyogurtshop-revathi
  template:
    metadata:
      name: frozenyogurtshop-revathi
      labels:
        app: frozenyogurtshop-revathi
    spec:
      containers:
      - name: ovs
        image: jaibw/frozenyogurtshop:latest 
        ports:
        - containerPort: 80 

---
apiVersion: v1
kind: Service
metadata:
  name: frozenyogurtshop-revathi
spec:
  type: NodePort
  ports:
  - targetPort: 80 
    port: 80
  selector:
    app: frozenyogurtshop-revathi
